[package]
name = "openapiv3"
version = "0.1.0"
authors = ["Glade Miller <glademiller@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.82", features = ["derive"]}
serde_json = "1.0.33"
serde_yaml = "0.8"
