[package]
name = "openapiv3"
version = "0.1.0"
authors = ["Glade Miller <glademiller@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["serde", "openapi", "v3"]

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
